esphome:
  name: esp-cam
  friendly_name: ESP CAM
#  libraries:
#    - esp32-camera=https://github.com/espressif/esp32-camera.git#v2.0.15

esp32:
  # 因esphome中对ESP32-s3主板名称支持不全，需要自己测试哪款主板型号适合自己比如我的n16r8
  board: esp32s3box
  framework:
    type: arduino
  variant: esp32s3
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: NONE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "BH7YYy8txrxIRy7GN2Qn4k5rwjuFbQjcAw5RFIs27uk="

ota:
  - platform: esphome
    password: "a5319aaaf9046719da45cc4c2dc3ae97"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Cam Fallback Hotspot"
    password: "12345678"

captive_portal:
    
# psram:
#   mode: octal
#   speed: 40MHz

external_components:
  - source:
      type: git
      url: https://github.com/miiky-ning/esphome_custom_components
    components: [ esp32_camera ]

esp32_camera:
  name: Wash Room Cam
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  resolution: 1920x1080
  max_framerate: 15fps
  jpeg_quality: 10
  contrast: 0 # 对比度
  brightness: 2 # 亮度
  saturation: 2 # 饱和度
  ae_level: 2 # 曝光级别
  agc_gain_ceiling: 4X
  wb_mode: OFFICE
  vertical_flip: false
  horizontal_mirror: true

esp32_camera_web_server:
  - port: 8080
    mode: stream

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
debug:
  update_interval: 10s

# text_sensor:
#   - platform: debug
#     device:
#       name: "Device Info"

sensor:
  - platform: debug
    psram:
      name: "Free PSRAM"